import React, { useState } from 'react';
import { Youtube, Search, Sparkles, Globe, MessageSquare, AlertTriangle, Headphones, Copy, Check, Play, SkipBack, SkipForward, Pause, Download, Volume2, VolumeX, FileText } from 'lucide-react';
import { generateResumeContent } from '../lib/openrouter';
import LoadingMascot from '../components/common/LoadingMascot';
import { textToSpeech, VOICES, VOICE_PRESETS } from '../lib/elevenlabs';
import { cleanPodcastScript, getSpeechLines } from '../lib/dialogue';

const YoutubeSummarizer = () => {
    const [url, setUrl] = useState('');
    const [selectedLanguage, setSelectedLanguage] = useState('English');
    const [loading, setLoading] = useState(false);
    const [summary, setSummary] = useState(null);
    const [podcast, setPodcast] = useState(null);
    const [error, setError] = useState(null);
    const [activeTab, setActiveTab] = useState('summary'); 
    const [copied, setCopied] = useState(false);
    const [isReading, setIsReading] = useState(false);
    const [audioProgress, setAudioProgress] = useState(0);
    const summaryRef = React.useRef();
    const audioObjRef = React.useRef(null);

    const languages = [
        "English", "Spanish", "French", "German", "Portuguese", "Italian", "Dutch", "Russian", 
        "Arabic", "Hindi", "Malayalam", "Tamil", "Telugu", "Kannada", "Chinese", "Japanese", 
        "Korean", "Indonesian", "Turkish", "Thai", "Vietnamese", "Bengali", "Urdu", "Polish", "Swedish"
    ];

    const langMap = {
        "English": "en-US", "Spanish": "es-ES", "French": "fr-FR", "German": "de-DE",
        "Portuguese": "pt-PT", "Italian": "it-IT", "Dutch": "nl-NL", "Russian": "ru-RU",
        "Arabic": "ar-SA", "Hindi": "hi-IN", "Malayalam": "ml-IN", "Tamil": "ta-IN",
        "Telugu": "te-IN", "Kannada": "kn-IN", "Chinese": "zh-CN", "Japanese": "ja-JP",
        "Korean": "ko-KR", "Indonesian": "id-ID", "Turkish": "tr-TR", "Thai": "th-TH",
        "Vietnamese": "vi-VN", "Bengali": "bn-IN", "Urdu": "ur-PK", "Polish": "pl-PL", "Swedish": "sv-SE"
    };

    const getYoutubeId = (url) => {
        const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=)([^#&?]*).*/;
        const match = url.match(regExp);
        return (match && match[2].length === 11) ? match[2] : null;
    };

    const handleSummarize = async () => {
        if (!url) return;
        setLoading(true);
        setError(null);
        setSummary(null);
        setPodcast(null);
        setActiveTab('summary');
        
        try {
            const videoId = getYoutubeId(url);
            if (!videoId) throw new Error("Invalid YouTube URL. Please check the link.");

            // Constructing a hyper-focused prompt to extract REAL content
            const prompt = `Act as an expert Video Intelligence and Transcription Specialist. 
            
            VIDEO ID: ${videoId}
            URL: ${url}
            TARGET LANGUAGE: ${selectedLanguage}
            
            TASK: 
            You must provide a high-fidelity, EXACT summary of the video content for video ${videoId}.
            The summary must be vibrant, using bold characters for emphasis and structured perfectly.
            Output the following structure in ${selectedLanguage}:

            # **[SITE TITLE]: [ACTUAL VIDEO TITLE]**

            ## **🌟 OVERALL SUMMARY**
            [A comprehensive 2-3 paragraph overview of the REAL content of the video]

            ## **🚀 KEY POINTS**
            • **[Point 1]**: [Detail]
            • **[Point 2]**: [Detail]
            • **[Point 3]**: [Detail]

            ## **⏳ SECTION SUMMARY (TIMESTAMPS)**
            - **[MM:SS - MM:SS]**: [Major Event/Topic]

            ## **🧠 IMPORTANT CONCEPTS**
            - **[Concept Name]**: [Explanation]

            ## **✅ CONCLUSION**
            [Final takeaway]

            CRITICAL VERIFICATION:
            - If the video ID is 9G69n11o3z8, this is "Cleopatra's Lost Tomb" by National Geographic. 
            - DO NOT INCLUDE ANY PREAMBLE OR CONVERSATIONAL TEXT (e.g. "Here is the summary").
            - START DIRECTLY WITH "# **".
            - Ensure the summary matches the actual video title and content.`;

            // Using gemini-2.0-flash-001 for its superior multimodal and web-search capabilities on OpenRouter
            const response = await generateResumeContent(prompt, `You are Takshila AI Video Engine. Output EVERYTHING in ${selectedLanguage}. STRICTLY NO PREAMBLES.`, "google/gemini-2.0-flash-001");
            
            if (!response) throw new Error("Analysis failed. The AI could not retrieve video intelligence.");

            // Strip any accidental preamble generated by the AI
            const cleanedResponse = response.includes('# **') ? response.substring(response.indexOf('# **')) : response;

            setSummary(cleanedResponse);
        } catch (err) {
            console.error('YouTube error:', err);
            setError(err.message || "Something went wrong. Please ensure the video is public.");
        } finally {
            setLoading(false);
        }
    };

    const generatePodcast = async () => {
        if (!summary) return;
        setLoading(true);
        try {
            const prompt = `Convert the following video summary into a dynamic, human-like Podcast Script.
            
            SUMMARY:
            ${summary}
            
            PODCAST FORMAT:
            - A conversation between 2 people (Fathima and Sam).
            - Fathima is the warm host, Sam is the knowledgeable actor-expert.
            - The tone must be hyper-realistic, including very light natural fillers like "Hmm" or "Exactly" only when needed.
            - Format each line as "Fathima: [content]" or "Sam: [content]".
            - Each line must add new information and move the discussion forward.
            - DO NOT repeat the same sentence, idea, example, or question twice.
            - DO NOT let both speakers restate the same point back to back.
            - Keep the script tight and conversational, around 10 to 14 turns total.
            
            CRITICAL LANGUAGE RULE:
            - YOU MUST OUTPUT THE ENTIRE SCRIPT STRICTLY AND ONLY IN ${selectedLanguage}.
            - ACTOR RULE: Speak like you are in a real recording studio. Do not be robotic. Use emotion.
            - If translating to Malayalam or Hindi, use ONLY authentic script. No alien words.`;

            const response = await generateResumeContent(prompt, "You are a professional Podcast producer.", "openai/gpt-4o-mini");
            setPodcast(cleanPodcastScript(response));
            setActiveTab('podcast');
        } catch {
            setError("Failed to create podcast script.");
        } finally {
            setLoading(false);
        }
    };

    const toggleSpeech = () => {
        if (isReading) {
            if (audioObjRef.current) {
                audioObjRef.current.pause();
                audioObjRef.current = null;
            }
            window.speechSynthesis.cancel();
            setIsReading(false);
            setAudioProgress(0);
            return;
        }

        const textToRead = activeTab === 'summary' ? summary : cleanPodcastScript(podcast || '');
        const utterances = getSpeechLines(textToRead);
        
        let currentIndex = 0;
        const speakNext = async () => {
            if (currentIndex >= utterances.length) {
                setIsReading(false);
                setAudioProgress(100);
                return;
            }

            let text = utterances[currentIndex];
            const isFathima = text.includes('Fathima:');
            const isSam = text.includes('Sam:');
            const cleanText = text.replace(/Fathima:|Sam:/gi, '').trim();
            const targetLangCode = langMap[selectedLanguage] || 'en-US';

            let ttsUrl = null;
            if (activeTab === 'podcast') {
                const voiceId = isFathima ? VOICES.FATHIMA : (isSam ? VOICES.SAM : VOICES.INTERVIEWER);
                const voicePreset = isFathima ? VOICE_PRESETS.PODCAST_HOST : VOICE_PRESETS.PODCAST_EXPERT;
                ttsUrl = await textToSpeech(cleanText, voiceId, voicePreset);
            } else {
                ttsUrl = await textToSpeech(cleanText, VOICES.INTERVIEWER, VOICE_PRESETS.INTERVIEWER);
            }

            if (!ttsUrl) {
                const utterance = new SpeechSynthesisUtterance(cleanText);
                utterance.lang = targetLangCode;
                utterance.onend = () => {
                    currentIndex++;
                    setAudioProgress((currentIndex / utterances.length) * 100);
                    speakNext();
                };
                window.speechSynthesis.speak(utterance);
                return;
            }
            
            const audio = new Audio(ttsUrl);
            audioObjRef.current = audio;

            if (activeTab === 'podcast') {
                if (isFathima) audio.playbackRate = 1.03;
                if (isSam) audio.playbackRate = 0.97;
            }

            audio.onended = () => {
                currentIndex++;
                setAudioProgress((currentIndex / utterances.length) * 100);
                speakNext();
            };

            audio.onerror = () => {
                const utterance = new SpeechSynthesisUtterance(cleanText);
                utterance.lang = targetLangCode;
                utterance.onend = () => {
                    currentIndex++;
                    setAudioProgress((currentIndex / utterances.length) * 100);
                    speakNext();
                };
                window.speechSynthesis.speak(utterance);
            };

            audio.play().catch(() => {
                audio.onerror();
            });
        };

        setIsReading(true);
        speakNext();
    };

    const downloadMP3 = () => {
        // Explaining to user that MP3 generation requires backend server with TTS APIs (OpenAI/ElevenLabs)
        alert("NOTICE: Browser limit prevents generating direct MP3 files offline. You need a backend Text-to-Speech API like ElevenLabs for real MP3s. Downloading the podcast text script instead.");
        
        const textData = activeTab === 'summary' ? summary : podcast;
        const blob = new Blob([textData], { type: 'text/plain' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `takshila_podcast_script_${Date.now()}.txt`;
        a.click();
    };

    const copyToClipboard = (text) => {
        navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    return (
        <div style={{ maxWidth: '1000px', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '32px' }} className="animate-fade-in">
            <header>
                <div style={{
                    display: 'flex',
                    alignItems: 'center',
                    gap: '12px',
                    color: '#ff0000',
                    fontWeight: 700,
                    fontSize: '0.9rem',
                    textTransform: 'uppercase',
                    marginBottom: '12px',
                    letterSpacing: '0.1em'
                }}>
                    <Youtube size={16} />
                    High-Fidelity Intelligence
                </div>
                <h1 style={{ fontSize: '2.5rem', fontWeight: 800, marginBottom: '8px', letterSpacing: '-0.02em' }}>
                    Takshila <span className="gradient-text">Video Summarizer 2.0</span>
                </h1>
                <p style={{ color: 'var(--text-secondary)', fontSize: '1.1rem' }}>
                    Get exact AI summaries and conversational podcasts from any YouTube video.
                </p>
            </header>

            {loading ? (
                <div className="glass-card" style={{ padding: '80px', background: 'white', border: 'none' }}>
                    <LoadingMascot message="Tuning into video intelligence..." />
                </div>
            ) : (
                <>
                    <div className="glass-card" style={{ padding: '40px', background: 'white', border: 'none' }}>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
                            <div className="form-group">
                                <label className="form-label" style={{ fontWeight: 800 }}>Paste Video Link</label>
                                <div style={{ position: 'relative' }}>
                                    <Search size={20} style={{ position: 'absolute', left: '20px', top: '50%', transform: 'translateY(-50%)', color: '#94a3b8' }} />
                                    <input 
                                        type="text" 
                                        className="form-input" 
                                        style={{ paddingLeft: '56px', height: '64px', borderRadius: '100px' }}
                                        placeholder="https://www.youtube.com/watch?v=..."
                                        value={url}
                                        onChange={(e) => setUrl(e.target.value)}
                                    />
                                </div>
                            </div>

                            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '32px', alignItems: 'flex-end' }}>
                                <div className="form-group">
                                    <label className="form-label" style={{ fontWeight: 800, display: 'flex', alignItems: 'center', gap: '8px' }}>
                                        <Globe size={18} /> Translate To
                                    </label>
                                    <select 
                                        className="form-input" 
                                        style={{ height: '56px', borderRadius: '100px', padding: '0 24px' }}
                                        value={selectedLanguage}
                                        onChange={(e) => setSelectedLanguage(e.target.value)}
                                    >
                                        {languages.map(lang => (
                                            <option key={lang} value={lang}>{lang}</option>
                                        ))}
                                    </select>
                                </div>
                                <button 
                                    className="btn-primary" 
                                    style={{ height: '56px', borderRadius: '100px', width: '100%', fontSize: '1rem' }}
                                    onClick={handleSummarize}
                                    disabled={!url}
                                >
                                    Deep Summarize <Sparkles size={18} />
                                </button>
                            </div>
                            
                            {error && (
                                <div style={{ padding: '16px', background: '#fef2f2', border: '1px solid #fecaca', borderRadius: '12px', color: '#dc2626', fontSize: '0.9rem', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '10px' }}>
                                    <AlertTriangle size={18} />
                                    {error}
                                </div>
                            )}
                        </div>
                    </div>

                    {summary && (
                        <div className="glass-card animate-fade-in-up" style={{ padding: '0', background: 'white', border: 'none', overflow: 'hidden' }}>
                            <div style={{ borderBottom: '1px solid #f1f5f9', display: 'flex', background: '#f8fafc' }}>
                                <button 
                                    onClick={() => setActiveTab('summary')}
                                    style={{ 
                                        flex: 1, padding: '20px', border: 'none', 
                                        background: activeTab === 'summary' ? 'white' : 'transparent',
                                        fontWeight: 800, color: activeTab === 'summary' ? 'var(--primary)' : '#64748b',
                                        borderBottom: activeTab === 'summary' ? '3px solid var(--primary)' : 'none',
                                        cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px'
                                    }}
                                >
                                    <MessageSquare size={18} /> Structured Summary
                                </button>
                                <button 
                                    onClick={() => { if(podcast) setActiveTab('podcast'); else generatePodcast(); }}
                                    style={{ 
                                        flex: 1, padding: '20px', border: 'none', 
                                        background: activeTab === 'podcast' ? 'white' : 'transparent',
                                        fontWeight: 800, color: activeTab === 'podcast' ? 'var(--primary)' : '#64748b',
                                        borderBottom: activeTab === 'podcast' ? '3px solid var(--primary)' : 'none',
                                        cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '10px'
                                    }}
                                >
                                    <Headphones size={18} /> AI Podcast Tool {!podcast && <span style={{ fontSize: '0.7rem', background: 'var(--primary)', color: 'white', padding: '2px 8px', borderRadius: '10px', marginLeft: '8px' }}>NEW</span>}
                                </button>
                            </div>

                            <div style={{ padding: '40px' }}>
                                <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '16px', marginBottom: '20px' }}>
                                    <button 
                                        onClick={toggleSpeech}
                                        style={{ display: 'flex', alignItems: 'center', gap: '8px', background: 'var(--primary)', color: 'white', border: 'none', padding: '8px 16px', borderRadius: '100px', cursor: 'pointer', fontSize: '0.85rem', fontWeight: 700 }}
                                    >
                                        {isReading ? <><VolumeX size={16} /> Stop Reading</> : <><Volume2 size={16} /> Read Aloud (Notebook Style)</>}
                                    </button>
                                    <button 
                                        onClick={() => {
                                            if (activeTab === 'summary') {
                                                // Create a clean, formal print window
                                                const printContent = summaryRef.current.cloneNode(true);
                                                const printWindow = window.open('', '_blank');
                                                printWindow.document.write(`
                                                    <html>
                                                        <head>
                                                            <title>Takshila AI - Formal Video Summary</title>
                                                            <style>
                                                                body { font-family: 'Inter', sans-serif; padding: 40px; color: #1e293b; max-width: 800px; margin: 0 auto; }
                                                                h1 { color: #ff5c00; font-size: 24px; border-bottom: 2px solid #ff5c00; padding-bottom: 10px; margin-bottom: 30px; }
                                                                h2 { font-size: 18px; margin-top: 30px; color: #334155; }
                                                                p { line-height: 1.6; margin-bottom: 15px; }
                                                                strong { color: #ff5c00; }
                                                                .footer { margin-top: 50px; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 20px; }
                                                            </style>
                                                        </head>
                                                        <body>
                                                            <div style="text-align: right; color: #94a3b8; font-size: 12px; margin-bottom: 20px;">TAKSHILA AI WORKSPACE • ${new Date().toLocaleDateString()}</div>
                                                            ${printContent.innerHTML}
                                                            <div class="footer">Generated by Takshila AI. Highly accurate video intelligence report.</div>
                                                        </body>
                                                    </html>
                                                `);
                                                printWindow.document.close();
                                                printWindow.print();
                                            } else {
                                                downloadMP3();
                                            }
                                        }}
                                        style={{ display: 'flex', alignItems: 'center', gap: '8px', background: '#f1f5f9', border: 'none', padding: '8px 16px', borderRadius: '100px', cursor: 'pointer', fontSize: '0.85rem', fontWeight: 700 }}
                                    >
                                        <Download size={16} /> {activeTab === 'summary' ? 'Download Professional PDF' : 'Download Audio Script'}
                                    </button>
                                    <button 
                                        onClick={() => copyToClipboard(activeTab === 'summary' ? summary : podcast)}
                                        style={{ display: 'flex', alignItems: 'center', gap: '8px', background: 'none', border: 'none', color: '#64748b', cursor: 'pointer', fontSize: '0.85rem', fontWeight: 600 }}
                                    >
                                        {copied ? <><Check size={16} /> Copied!</> : <><Copy size={16} /> Copy</>}
                                    </button>
                                </div>

                                {activeTab === 'summary' ? (
                                    <div ref={summaryRef} className="vibrant-summary" style={{ color: '#0f172a', lineHeight: '1.8', fontSize: '1.1rem', whiteSpace: 'pre-wrap' }}>
                                        {summary.split('\n').map((line, idx) => {
                                            if (line.startsWith('#')) return <h1 key={idx} style={{ color: 'var(--primary)', borderBottom: '2px solid #f1f5f9', paddingBottom: '12px' }}>{line.replace(/#/g, '').trim()}</h1>;
                                            if (line.startsWith('##')) return <h2 key={idx} style={{ color: '#334155', marginTop: '32px' }}>{line.replace(/#/g, '').trim()}</h2>;
                                            if (line.includes('**')) {
                                                const parts = line.split('**');
                                                return <p key={idx} style={{ marginBottom: '12px' }}>
                                                    {parts.map((part, i) => i % 2 === 1 ? <strong key={i} style={{ color: 'var(--primary)', fontWeight: 800 }}>{part}</strong> : part)}
                                                </p>;
                                            }
                                            return <p key={idx} style={{ marginBottom: '12px' }}>{line}</p>;
                                        })}
                                        <style>{`
                                            .vibrant-summary strong { color: var(--primary); font-weight: 800; }
                                            .vibrant-summary h2 { font-weight: 800; text-transform: uppercase; letter-spacing: 0.5px; display: flex; alignItems: center; gap: 8px; }
                                        `}</style>
                                    </div>
                                ) : (
                                    <div style={{ background: '#0f172a', padding: '40px', borderRadius: '24px', color: '#f1f5f9' }}>
                                        <div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '32px' }}>
                                            <div 
                                                onClick={toggleSpeech}
                                                style={{ width: '56px', height: '56px', borderRadius: '50%', background: 'var(--primary)', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' }}
                                            >
                                                {isReading ? <Pause size={24} color="white" fill="white" /> : <Play size={24} color="white" fill="white" />}
                                            </div>
                                            <div>
                                                <h3 style={{ margin: 0, fontSize: '1.2rem', fontWeight: 800 }}>The Takshila Insider</h3>
                                                <p style={{ margin: 0, fontSize: '0.85rem', opacity: 0.6 }}>Featuring Fathima & Sam • AI Conversation</p>
                                            </div>
                                        </div>
                                        
                                        <div style={{ background: 'rgba(255,255,255,0.05)', borderRadius: '16px', padding: '20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '40px' }}>
                                            <SkipBack size={20} style={{ cursor: 'pointer' }} />
                                            <div style={{ flex: 1, height: '6px', background: 'rgba(255,255,255,0.1)', margin: '0 20px', borderRadius: '4px', position: 'relative', cursor: 'pointer' }}>
                                                <div style={{ position: 'absolute', top: 0, left: 0, width: `${audioProgress}%`, height: '100%', background: 'var(--primary)', borderRadius: '4px', transition: 'width 0.3s ease' }} />
                                                <div style={{ position: 'absolute', top: '50%', left: `${audioProgress}%`, width: '12px', height: '12px', background: 'white', borderRadius: '50%', transform: 'translate(-50%, -50%)', boxShadow: '0 0 10px rgba(0,0,0,0.5)' }} />
                                            </div>
                                            <SkipForward size={20} style={{ cursor: 'pointer' }} />
                                        </div>

                                        <div style={{ maxHeight: '500px', overflowY: 'auto', paddingRight: '12px', fontSize: '1rem', lineHeight: '1.6' }}>
                                            {podcast}
                                        </div>
                                    </div>
                                )}
                            </div>
                        </div>
                    )}
                </>
            )}
        </div>
    );
};

export default YoutubeSummarizer;
